language: julia
os:
  - linux
  - osx
  - windows
  - freebsd
arch:
  - amd64
  - i386
  - arm64
julia:
  - 1.0
  - 1
  - nightly
matrix:
  exclude:
    - os: osx
      arch: i386
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
    - os: freebsd
      arch: i386
    - os: freebsd
      arch: arm64
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
