language: julia
#os:
#  - linux
#  - osx
#  - windows
matrix:
  include:
    - os: windows
      arch: x64
      julia: 1.0
    - os: windows
      arch: x86
      julia: 1.0
#julia:
#  - 1.0
#  - 1.1
#  - nightly
notifications:
  email: false
#after_success:
#  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
